[package]
name = "trade-locker-connector"
version = "0.4.13"
edition = "2021"
authors = ["gorin <mxmgorin@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
http = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_derive = "*"
tokio = { version = "*", features = ["full"] }
async-trait = "*"
futures = "*"
futures-util = { version = "*", default-features = false }
reqwest = { version = "*", features = ["json"] }
error-chain = { version = "0.12.4", default-features = false }
serde_qs = "*"
chrono = { version = "*", features = ["serde"] }
md5 = "0.7.0"
strum = { version = "0.26", features = ["derive"] }
rust_socketio = "*"